### ISSUE TITLE
(이준희 조언)분업 및 협업 과정에서 당부사항

### ISSUE THREAD

**Issue by junhee0110** [uush/AutoCurtain_DY5th#18]
안녕하세요 여러분!!

다들 작업 잘하고 계신가요?

갈아 엎기 이전보다는 훨씬 진행이 잘 되는 것 같아서 보기 좋습니다!!

저번 회의에서 여러분이 작성 중인 코드를 쭉 읽어 보았습니다. 

쭉 읽어보았을 때 우려되는 부분이 조금 있어 당부의 말씀을 드리고자 합니다.

# 1. 기능 하나 하나를 함수로 작성하세요

다음의 코드를 예시로 들겠습니다.

한 사람이 LED 4개로 파도타기를 하는 기능을 구현 중이라고 가정합시다.

그 사람이 본인의 branch에 아래의 코드를 push합니다.

```c
int led_pin[4] = {10, 11, 12, 13};

void setup()
{
    for(int i = 0; i < 4; i++)
        pinMode(led_pin[i], OUTPUT);
}

void loop()
{
    for(int i = 0; i < 4; i++)
    {
    for(int j = 0; i < 4; i++)
        digitalWrite(led_pin[j], 0);

    digitalWrite(led_pin[i], 1);

    delay(1000);
}
```
여러분이 현재 기능을 구현하실 때 위의 코드처럼 구현하셨습니다. (기능을 loop내부에 구현)
위의 코드는 워낙 짧고 간단하지만, 여러분들이 구현하시는 엔코더, 모터 등은 길고 복잡합니다.
게다가, 그 많은 기능을 하나로 뭉치는 과정이 너무 힘들지 않을까요??

여러분들은 아래와 같이 기능을 구현하셔야 합니다.

```c
int led_pin[4] = {10, 11, 12, 13};

void setup()
{
    for(int i = 0; i < 4; i++)
        pinMode(led_pin[i], OUTPUT);
}

void loop()
{
    led_wave();
}

void led_wave()
{
    for(int i = 0; i < 4; i++)
    {
    for(int j = 0; i < 4; i++)
        digitalWrite(led_pin[j], 0);

    digitalWrite(led_pin[i], 1);
   
    delay(1000);
}
```

LED 파도타기 기능을 led_wave라는 함수로 정리했습니다. 
main loop에서는 그저 이 함수를 호출함으로써 더욱 보기 간편해졌습니다.

따라서, 여러분들이 구현하시는 기능들도 **꼭 함수로 정의해두시길 바랍니다!!**

# 파일을 분할합시다!

지금은 관으로 가버린 아두이노 스터디에서 파일분할하는 방법을 알려드렸습니다.
파일을 분할하지 않고, 함수 정의나 기능 구현을 아래로 쭉 써 내려가시면 나중에 버그를 수정하거나 유지보수가 힘들어집니다.
마치, 엄청 긴 소설에서 특정 내용을 찾아내기 힘든것처럼요!

그래서 꼭 파일 분할을 하셔야합니다!!

파일 분할을 하실때는 .h로 끝나는 헤더 파일과 .ino로 끝나는 소스코드를 작성하시면 되는데
헤더파일에는 함수의 선언, 소스코드에는 함수의 정의를 하면됩니다!

잘 모르시겠으면 main branch를 참고하세요!! 승혜 누나가 파일을 분할하여 기능을 구현했습니다!!

# 마무리

위의 내용이 잘 이해가 안될 수 있겠지만, 겪어보시면 왜 필요한지 아실거에요!
이거는 추천도 건의도 아니고, 반드시 해야 하는 것이니 모르는 것이 있으면 질문해주세요!!

**Comment by IamJunhee** [comment]
조언 및 게시글은 Discussion으로 이동합니다!
